apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: prometheus-operator
    addonmanager.kubernetes.io/mode: Reconcile
  name: prometheus-operator
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    k8s-app: prometheus-operator
