apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
    addonmanager.kubernetes.io/mode: Reconcile
  name: grafana
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: grafana
